// Package activities contains the four Temporal activities for Phase 2.
//
// Design principles:
//   - Every activity is idempotent: calling it twice with the same inputs
//     produces the same outcome with no duplicate side effects.
//   - Activities receive only serialisable scalar arguments — no unexported
//     types, no interface values.  This is a hard Temporal requirement.
//   - Repository and Redis dependencies are injected via the Activities struct;
//     the worker registers the struct's methods so Temporal can discover them.
package activities

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"go.temporal.io/sdk/activity"

	"github.com/tanisha/ach-retry-orchestrator/internal/db"
	"github.com/tanisha/ach-retry-orchestrator/internal/domain"
	achredis "github.com/tanisha/ach-retry-orchestrator/internal/redis"
)

// SubmitToACHInput is the argument passed to SubmitToACH.
// All fields must be JSON-serialisable (Temporal default codec).
type SubmitToACHInput struct {
	PaymentID     uuid.UUID
	Amount        string // decimal string — avoid float64 for money
	AccountNumber string
	RoutingNumber string
	TraceNumber   string // generated by the workflow before calling this activity
}

// SubmitToACHOutput carries the trace number back to the workflow.
type SubmitToACHOutput struct {
	TraceNumber string
}

// PersistStateTransitionInput carries everything UpdatePaymentState needs.
type PersistStateTransitionInput struct {
	PaymentID uuid.UUID
	FromState domain.PaymentState
	ToState   domain.PaymentState
	Reason    string
}

// Activities holds the live dependencies injected at worker startup.
// Register its methods with the Temporal worker — not the struct itself.
type Activities struct {
	Repo        *db.Repository
	RedisClient *achredis.Client
}

// ────────────────────────────────────────────────────────────────────────────
// Activity: SubmitToACH
// ────────────────────────────────────────────────────────────────────────────

// SubmitToACH simulates submitting a payment to the ACH network.
//
// In production this would build a NACHA file entry and POST it to your
// bank's API.  For Phase 2 we log the submission and return the caller-
// supplied trace number so the workflow can track it.
//
// Idempotency: the trace number is generated by the workflow before this
// activity is called, so retries pass the same trace number and produce the
// same output without double-submitting.
func (a *Activities) SubmitToACH(ctx context.Context, input SubmitToACHInput) (SubmitToACHOutput, error) {
	logger := activity.GetLogger(ctx)

	logger.Info("ACH submission",
		"payment_id", input.PaymentID,
		"amount", input.Amount,
		"routing_number", input.RoutingNumber,
		"account_number_last4", last4(input.AccountNumber),
		"trace_number", input.TraceNumber,
		"submitted_at", time.Now().UTC().Format(time.RFC3339),
	)

	// Simulate network latency / ACH gateway call.
	// Replace with real HTTP call in Phase 3/4.

	return SubmitToACHOutput{TraceNumber: input.TraceNumber}, nil
}

// ────────────────────────────────────────────────────────────────────────────
// Activity: PersistStateTransition
// ────────────────────────────────────────────────────────────────────────────

// PersistStateTransition writes a state change to PostgreSQL by calling
// repository.UpdatePaymentState, which enforces the FSM and writes the
// audit log in the same transaction.
//
// Idempotency: UpdatePaymentState is a no-op if the payment is already in
// ToState (the FSM transition table rejects invalid transitions, and a
// transition to the current state returns an error that we swallow here).
// In practice Temporal's at-least-once execution means this activity may be
// called multiple times on crash-recovery; the database constraint protects us.
func (a *Activities) PersistStateTransition(ctx context.Context, input PersistStateTransitionInput) error {
	logger := activity.GetLogger(ctx)

	payment, err := a.Repo.GetPaymentByID(ctx, input.PaymentID)
	if err != nil {
		return fmt.Errorf("PersistStateTransition: get payment %s: %w", input.PaymentID, err)
	}

	// If already in the target state, this activity has already succeeded on a
	// previous attempt — return nil to satisfy Temporal's at-least-once model.
	if payment.State == input.ToState {
		logger.Info("PersistStateTransition: already in target state, skipping",
			"payment_id", input.PaymentID,
			"state", input.ToState,
		)
		return nil
	}

	if err := a.Repo.UpdatePaymentState(ctx, payment, input.ToState, input.Reason); err != nil {
		return fmt.Errorf("PersistStateTransition: update payment %s to %s: %w",
			input.PaymentID, input.ToState, err)
	}

	logger.Info("PersistStateTransition: success",
		"payment_id", input.PaymentID,
		"from", input.FromState,
		"to", input.ToState,
		"reason", input.Reason,
	)
	return nil
}

// ────────────────────────────────────────────────────────────────────────────
// Activity: CheckIdempotency
// ────────────────────────────────────────────────────────────────────────────

// CheckIdempotencyInput is the argument to CheckIdempotency.
type CheckIdempotencyInput struct {
	TraceNumber string
}

// CheckIdempotencyOutput tells the workflow whether to proceed with submission.
type CheckIdempotencyOutput struct {
	// AlreadySubmitted is true when the trace number is already in Redis.
	// The workflow MUST short-circuit and skip SubmitToACH when this is true.
	AlreadySubmitted bool
}

// CheckIdempotency queries Redis for the trace number.
//
// Idempotency: a read-only operation — safe to retry unconditionally.
func (a *Activities) CheckIdempotency(ctx context.Context, input CheckIdempotencyInput) (CheckIdempotencyOutput, error) {
	err := a.RedisClient.CheckIdempotency(ctx, input.TraceNumber)
	if err == achredis.ErrTraceExists {
		return CheckIdempotencyOutput{AlreadySubmitted: true}, nil
	}
	if err != nil {
		return CheckIdempotencyOutput{}, fmt.Errorf("CheckIdempotency: %w", err)
	}
	return CheckIdempotencyOutput{AlreadySubmitted: false}, nil
}

// ────────────────────────────────────────────────────────────────────────────
// Activity: StoreTraceNumber
// ────────────────────────────────────────────────────────────────────────────

// StoreTraceNumberInput is the argument to StoreTraceNumber.
type StoreTraceNumberInput struct {
	TraceNumber string
}

// StoreTraceNumber writes the trace number into Redis with a 7-day TTL.
//
// Idempotency: uses SET NX internally — duplicate calls are no-ops.
func (a *Activities) StoreTraceNumber(ctx context.Context, input StoreTraceNumberInput) error {
	if err := a.RedisClient.StoreTraceNumber(ctx, input.TraceNumber); err != nil {
		return fmt.Errorf("StoreTraceNumber: %w", err)
	}
	activity.GetLogger(ctx).Info("StoreTraceNumber: stored",
		"trace_number", input.TraceNumber,
		"ttl_days", 7,
	)
	return nil
}

// ────────────────────────────────────────────────────────────────────────────
// Helper
// ────────────────────────────────────────────────────────────────────────────

// last4 returns the last 4 characters of s, or s itself if shorter.
// Used to avoid logging full account numbers.
func last4(s string) string {
	if len(s) <= 4 {
		return s
	}
	return s[len(s)-4:]
}

// GenerateTraceNumber returns a new collision-resistant trace number.
// Format: "ACH-" + first 8 hex chars of a UUID v4.
// Called by the workflow (not an activity) because it has no side effects.
func GenerateTraceNumber() string {
	id := uuid.New()
	return fmt.Sprintf("ACH-%s", id.String()[:8])
}
